var worldMap = [
    [
        '1    P',
        'BBBBBB',
        'WWWWWW',
        'p    2'
    ],
    [
        '      B',
        '      P',
        '    BBB',
        '1 B B  ',
        'BBBBBB ',
        ' WWWWWW',
        '  W W 2',
        'WWW    ',
        'p      ',
        'W      ',
    ],
    [
        'B B       ',
        'BP B    1B',
        'BBBBBBBBBB',
        'WWWWWWWWWW',
        'Wp W   2 W',
        '         W'
    ],
    [
        '1      P',
        'BBXBBXXB',
        'WxxWWxWW',
        'p      2'
    ],
    [
        'W  p     B',
        'W  W  B 1B',
        'WW    X BB',
        'WW x    BB',
        'W2 W  B  B',
        'W     P  B',
    ],
    [
        '2W  ',
        'WP  ',
        '    ',
        '    ',
        '  pB',
        '  B1',
    ],
    [
        ' P        1B',
        ' BBBBXXXTBBB',
        'WWWtxxxWWWW ',
        'W2        p ',
    ],
    [
        'WWWxWWW',
        'W     W',
        'W2   pW',
        'WWWtWWW',
        'BBBBBBB',
        'BP   1B',
        'BBBBBBB',
        '       ',
    ],
    [
        'B            B',
        'B1          PB',
        'BBTXXTXXTXXBBB',
        'WWWxxtxxtxxtWW',
        'Wp          2W',
        'W            W',
    ],
    [
        'X      W   ',
        'X      W2  ',
        'X1     WWWx',
        'XBBBX     W',
        '   B       ',
        '   B       ',
        '   BBB   W ',
        '   BB    pw',
        'XBBB       ',
        'B BP       ',
    ],
    [
        'WWWp   WW   ',
        'W  WW   W   ',
        'W     WWW   ',
        'W   W   W   ',
        'W2W     W   ',
        'WWWWWWWWW   ',
        'BBBBBBBBBBBB',
        'BBBB    B 1B',
        'BBBBB B    B',
        'BBB        B',
        'BB  BBBBBBBB',
        'BP          ',
    ],
    [
        '      W2W',
        '      W W',
        '      W W',
        '      W W',
        'WWWWWWW W',
        'BPB   w W',
        'B B   WpW',
        'B BBBBBBB',
        'B B      ',
        'B B      ',
        'B B      ',
        'B1B      ',
    ],
    []
];